SourceCode/ExpensesManager.Web/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Castle.Core.Logging;
using ExpensesManager.BusinessLogic.Criteria;
using ExpensesManager.BusinessLogic.Interfaces;
using ExpensesManager.DataAccess.DataModel;
using ExpensesManager.Web.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

namespace ExpensesManager.Web.Controllers
{
    [Authorize]
    [HandleError] 
    public class ExpenseController : Controller
    {
        public ILogger Logger { get; set; }
        public IExpenseService ExpenseService { get; set; }

        public ActionResult Index()
        {
            return View("Index", new ExpenseModel());
        }

        /// <summary>
        /// Create the new Expense
        /// </summary>
        /// <param name="expenseModel">Expense to be created</param>
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(ExpenseModel expenseModel)
        {
            if (!ModelState.IsValid)
            {
                if (expenseModel.Amount <= 0)
                {
                    return Json(new {success = false, message = "Amount should be greater then zero"});
                }

                if (expenseModel.CategoryId <= 0)
                {
                    return Json(new { success = false, message = "Please select a category" });
                }

                if (expenseModel.SubCategoryId <= 0)
                {
                    return Json(new { success = false, message = "Please select a subcategory" });
                }

                return Json(new { success = false, message = "Validation error" });
            }
            try
            {
                var expense = ExpenseService.SaveExpense(
                    new Expense
                    {
                        CategoryId = expenseModel.CategoryId,
                        SubCategoryId = expenseModel.SubCategoryId,
                        Description = expenseModel.Description.Trim(),
                        Date = expenseModel.Date,
                        Amount = expenseModel.Amount
                    });

                return Json(new { success = true, message = expense.Id });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        public ActionResult GetExpenses([DataSourceRequest] DataSourceRequest request)
        {
            var expenses = ExpenseService.FindExpenses(new ExpenseCriteria());

            if (expenses != null && expenses.Count > 0)
            {
                return Json(expenses.Select(e =>
                                          new ExpenseModel
                                          {
                                              Id = e.Id,
                                              Amount = e.Amount,
                                              Date = e.Date,
                                              Description = e.Description,
                                              CategoryId = e.CategoryId,
                                              SubCategoryId = e.SubCategoryId,
                                              CategoryName = e.CategoryName,
                                              SubCategoryName = e.SubCategoryName
                                          }).ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            }
            return Json(new List<ExpenseModel>().ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Delete(ExpenseModel expenseModel)
        {
            try
            {
                ExpenseService.Delete(expenseModel.Id);

                return Json(new { success = true, message = expenseModel.Id });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Update(ExpenseModel expenseModel)
        {
            try
            {
                var expense = ExpenseService.SaveExpense(
                    new Expense
                    {
                        Id = expenseModel.Id,
                        CategoryId = expenseModel.CategoryId,
                        SubCategoryId = expenseModel.SubCategoryId,
                        Description = expenseModel.Description.Trim(),
                        Date = expenseModel.Date,
                        Amount = expenseModel.Amount
                    });

                return Json(new { success = true, message = expense.Id });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }
    }
}

SourceCode/ExpensesManager.Web/Views/Expense/Index.cshtml
@using ExpensesManager.Web.Models
@model ExpenseModel

@{
    ViewBag.Title = "Manage Expenses";
}

@using (Ajax.BeginForm("Create", "Expense", null,
        new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST", LoadingElementId = "spinner",
                          OnBegin = "ajaxValidate()",
                          OnSuccess = "Expense.OnSuccess",
                          OnFailure = "Expense.OnFaliure"
        },
        new { enctype = "multipart/form-data", id = "expenseForm" } ))
    {
    <div class="demo-section">
        <br />
        <label>Expenses</label><br />
        <div id="NewExpenses">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <table>
                <tr>
                    <td><div class="site-editor-label">@Html.LabelFor(m => m.Date)</div></td>
                    <td style="width: 170px;">
                        <div class="site-editor-field" style="width: 170px;">
                            @Html.EditorFor(m => m.Date)
                            @Html.ValidationMessageFor(m => m.Date)
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><div class="site-editor-label">@Html.LabelFor(m => m.Description)</div></td>
                    <td>
                        <div class="site-editor-field">
                            @Html.EditorFor(m => m.Description)
                            @Html.ValidationMessageFor(m => m.Description)
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><div class="site-editor-label"><label>Category</label></div></td>
                    <td>
                        <div class="site-editor-field">
                           <div class="site-editor-field">
                                @Html.DropDownListFor(m => m.CategoryId, Enumerable.Empty<SelectListItem>(), "Select category...")
                                @Html.ValidationMessageFor(m => m.CategoryId)
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><div class="site-editor-label"><label>SubCategory</label></div></td>
                    <td>
                        <div class="site-editor-field">
                            <div class="site-editor-field">
                                @Html.DropDownListFor(m => m.SubCategoryId, Enumerable.Empty<SelectListItem>(), "Select subcategory...")
                                @Html.ValidationMessageFor(m => m.SubCategoryId)
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><div class="site-editor-label">@Html.LabelFor(m => m.Amount)</div></td>
                    <td>
                        <div class="site-editor-field">
                            @Html.EditorFor(m => m.Amount)
                            @Html.ValidationMessageFor(m => m.Amount)
                        </div>
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;"><a href="javascript:void(0);" id="submitButton">Add expense</a></td>
                    <td><span style="color: red;" id="errorText"></span></td>
                </tr>
            </table>
        </div>
       
    </div>
}

<div>
    <br />
    <label>Submitted</label><br />
    <div id="ExpensesGrid"></div>
</div>

<style scoped>
    .demo-section {
        padding: 30px;
    }

        .demo-section h2 {
            text-transform: uppercase;
            font-size: 1.2em;
            margin-bottom: 30px;
        }

        .demo-section label {
            display: inline-block;
            width: 120px;
            padding-right: 5px;
            text-align: right;
        }

        .demo-section .k-button {
            margin: 20px 0 0 125px;
        }

    .k-readonly {
        color: gray;
    }
</style>

<div id="confirmationWindow"><span id="confirmationWindowText"></span></div> 
<div id="uploaderImagePreviewWindow"><div id="imagePreview" style="text-align: center; vertical-align: central;"></div></div>
<div id='spinner' style='display:none'><img src='/Images/loading.gif' class="ajax-loader" alt='Processing...' /></div>   

@section scripts {
    @Scripts.Render("~/bundles/layoutscripts")

    <script>
        $(document).ready(function () {
            Expense.init();
        });
    </script>
}